### ISSUE TITLE
Broken compilation with GHC 7.6.3

### ISSUE THREAD

**Issue by asr** [asr/apia#30]
Reported [here](https://travis-ci.org/asr/apia/jobs/130307793) by Travis:

```
make install-bin
...
src/Apia/ATPs.hs:85:5:
    Module `System.Process' does not export `callProcess'
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
apia-1.0.1 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by asr** [comment]
@jorgeacv2 Can you reproduce the issue?

**Comment by asr** [comment]
I couldn't reproduce the issue.

**Comment by jorgeacv2** [comment]
> @jorgeacv2 https://github.com/jorgeacv2 Can you reproduce the issue?

No, Sr. Type check and appears

xxx/src$ apia --check --atp=vampire --atp=e PropertiesATP.agda
apia: The reading of the interface file
/home/ja/thesis/src/PropertiesATP.agdai failed. It is possible that you
used a different version of Agda to build the Apia program and to
type-check your module

My GHC is 7.6.3

**Comment by asr** [comment]
> No, Sr. Type check 

Thanks for the feedback!

> xxx/src$ apia --check --atp=vampire --atp=e PropertiesATP.agda apia: The reading of the interface file /home/ja/thesis/src/PropertiesATP.agdai failed. It is possible that you used a different version of Agda to build the Apia program and to type-check your module 

Before running Apia you need to run:

```
$ agda PropertiesATP.agda
```

**Comment by jorgeacv2** [comment]
> Before running Apia you need to run:
> 
> $ agda PropertiesATP.agda

Yes sr. 

Jorge Acevedo Acosta
