### ISSUE TITLE
Missing `--no-config-file` command-line option

### ISSUE THREAD

**Issue by asr** [asr/apia#84]
For debugging purpose, I miss a `--no-config-file` command-line option which tells to Apia does not use the `.apia` file.

**Comment by jonaprieto** [comment]
It seems just ignore it in the `getDefaults` function at the end of the Defaults.hs module.

```Haskell
  let allFiles ∷ [FilePath]
      allFiles = userFiles ++ [defaultApia]
```
Replacing it with something like: 

```Haskell
  let allFiles ∷ [FilePath]
      allFiles = (if optNoConfigFile opts then [] else userFiles) ++ [defaultApia]
```

where optNoConfigFile is assigned to handle `--no-config-file` command line option.

**Comment by asr** [comment]
> Replacing it with something like: 
```Haskell
  let allFiles ∷ [FilePath]
      allFiles = (if optNoConfigFile opts then [] else userFiles) ++ [defaultApia]
```
That replace didn't work because I have no access to the current options (i.e. your `opts`) when defining `allFiles`.
